apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: manual   # must match the PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi            # must be <= PV capacity
  volumeName: mysql-pv        # bind directly to your PV
