apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer-role
rules:
  - apiGroups: [""] 
    resources: ["ConfigMap"]
    verbs: ["get", "list"]
  - apiGroups: [""] 
    resources: ["pods"]
    # resourceName: ["nginx-pod"]  -- to give access for specific pod
    verbs: ["get", "list",]
  # - apiGroups: [""]
  #   resources: ["nodes"]
  #   # resourceName: ["172-32-45-10.ec2.internal"]  -- to give access for specific node
  #   verbs: ["get", "list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
